### ISSUE TITLE
Patch operations for loop issue

### ISSUE THREAD

**Issue by mobitar** [xwiki-contrib/chainpad#11]
https://github.com/xwiki-contrib/chainpad/blob/master/chainpad.dist.js#L960

```
        for (var i = 0; i < realtime.changeHandlers.length; i++) {
            for (var j = patch.operations.length; j >= 0; j--) {
                var op = patch.operations[j];
                realtime.changeHandlers[i](op.offset, op.toRemove, op.toInsert);
            }
        }
```

This line:

```
 for (var j = patch.operations.length; j >= 0; j--) {
```

should be:

```
 for (var j = patch.operations.length - 1; j >= 0; j--) {
```

Otherwise, if you have only one operation, you'd start out at patch.operations[1], which is out of bounds.

**Comment by sdumitriu** [comment]
@mobitar Why not submit a pull request instead?

**Comment by mobitar** [comment]
@sdumitriu done.

**Comment by cjdelisle** [comment]
This should be fixed now in the big refactoring. Thanks for your patience.
